@startuml
participant content
participant browser
participant background
participant storage
participant alarm

content->background: register word
background->storage: register word in \nstorage.words-<srcLang><dstLang>
background->alarm: set alarm for quiz time
...wait for alarm time...
alarm-> background: ring alarm
background->storage: add to storage.quizQueue
background->browser: badge shows number of ready quiz
...user opens popup...
browser->background: request quiz
background->browser: respond next quiz
...user answers quiz...
browser->background: send answer
background->storage: drop first element in storage.quizQueue
background->browser: update badge
background->storage: check answer &\nincrement corresponding correctCount
background->alarm: set alarm again for the word
background->browser: respond result and answer
...user press next quiz button...
browser->background: request quiz
...same as above...
@enduml
